language: python
sudo: false
cache: pip

python:
  - "2.7"
#  - "3.4"

before_install:
  - pip install -U pip

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install Cython
  - pip install coveralls
  - pip install coverage
  - python setup.py install

script:
  - coverage run --source respy/ -m pytest


after_success:
  - coveralls